[Wing]
spar_box_x_c = 0.4
x_wing_box = "57 ft"
airfoil = "C.air"
maxSpan = "117.5 ft"
hweb_to_hbox = 0.75
strut_local_velocity_ratio = 1.0
outer_panel_taper_ratio = 0.25
sweep = 26.0
z_strut = "154 in"
panel_break_location = 0.285
box_width_to_chord = 0.5
spanbreak_thickness_to_chord = 0.1266
center_box_halfspan = "71.0 in"
has_strut = false
AR = 10.1
strut_toc = 0.15
inner_panel_taper_ratio = 0.7
root_thickness_to_chord = 0.1268
z_wing = "-5.5 ft"

    [Wing.Weightfracs]
    spoilers = 0.02
    leading_trailing_edge = 0.1
    aileron = 0.04
    flap = 0.2
    slat = 0.1
    ribs = 0.15
    attachments = 0.03

    [Wing.Aero]
    strut_lowspeed_cdf = 0.0085
    wing_tip_lift_rolloff_factor = -0.05
    excrescence_drag_factor = 1.02
    Re_ref = 2.0e7
    lowspeed_cdf = 0.0085
    strut_lowspeed_cdp = 0.0035
    fuselage_lift_carryover_loss_factor = -0.3
    Reynolds_scaling = -0.15
    lowspeed_cdp = 0.0035
    strut_Re_ref = 1.0e6
    BLI_frac = 0.0

        [Wing.Aero.Landing]
        clt_clo = 0.5
        cm_o = -0.35
        cm_t = -0.02
        cls_clo = 1.1
        cm_s = -0.35

        [Wing.Aero.Takeoff]
        clt_clo = 0.6
        cm_o = -0.2
        cm_t = -0.02
        cls_clo = 1.1
        cm_s = -0.2

        [Wing.Aero.Climb]
        clt_clo = 0.9
        cm_o = -0.06
        cm_t = -0.06
        cls_clo = 1.238
        cm_s = -0.06

["Aircraft Description"]
name = "TASOPT Model with cryo fuel and HX"
description = """737-800\r\n    This file is a slightly modified version of the default TASOPT file. It replaces the fuel\r\n    with liquid hydrogen and makes the corresponding fuel system changes such as fuselage storage and insulation. It\r\n    also demonstrates the heat exchanger capabilities in the engine model.\r\n    """

[Mission]
N_missions = 1
payload = ["180 pax"]
exit_limit = 189
weight_per_pax = "215.0 lbf"
max_payload = "189 pax"
range = "3000.0 nmi"
fuel_reserves = 0.2
Nlift = 3.0
Vne = "280 kts"

    [Mission.Descent]
    descent_angle_bottom-of-descent = "-3.0 deg"
    descent_angle_top-of-descent = "-3.0 deg"

    [Mission.Takeoff]
    CD_dead_engine = 0.5
    max_balanced_field_length = "8000.0 ft"
    rolling_resistance_coeff = 0.025
    takeoff_T = 288.2
    takeoff_obstacle_height = "35 ft"
    braking_resistance_coeff = 0.35
    CL_max_perp = 2.25
    takeoff_alt = "0.0 ft"
    Nland = 6.0
    CD_spoilers = 0.1
    CD_landing_gear = 0.015

    [Mission.Climb]
    minimum_top-of-climb_gradient = 0.015

    [Mission.Cruise]
    cruise_mach = 0.8
    cruise_CL = 0.57
    cruise_alt = "35000.0 ft"

[Fuselage]
cabin_pressure_altitude = "8000.0 ft"

    [Fuselage.Aero]
    CL_zero_fuse_moment = 0.185
    excrescence_drag_factor = 1.03
    wingbreak_fuse_overspeed = 0.014
    fuse_moment_volume_deriv = "2390.0 ft3"
    wingroot_fuse_overspeed = 0.018
    wingtip_fuse_overspeed = 0.0045
    BLI_frac = 0.0

    [Fuselage.Weights]
    window_per_length = 435.0
    additional = 0.2
    floor_weight_per_area = 60.0
    stringer = 0.35
    seat_weight_fraction = 0.1
    custom_weight_delta = 0.0
    HPE_sys_weight_fraction = 0.01
    APU_weight_fraction = 0.035
    add_payload_weight_fraction = 0.35
    frame = 0.25
    window_insul_per_area = 22.0
    fixed_weight = "3000 lbf"

    [Fuselage.Geometry]
    HT_load_fuse_bend_relief = 0.4
    a_nose = 1.65
    x_cone_end = "117 ft"
    x_end = "124 ft"
    double_decker = false
    tapers_to = "point"
    VT_load_fuse_bend_relief = 0.7
    x_pressure_shell_aft = "102 ft"
    x_APU = "120 ft"
    radius = "100 in"
    y_critical_engines = "16 ft"
    front_seat_offset = "10 ft"
    seat_pitch = "30 in"
    aisle_halfwidth = "10 in"
    calculate_cabin_length = true
    rear_seat_offset = "5 ft"
    x_start_cylinder = "20 ft"
    x_HPE_sys = "62ft"
    seat_width = "19 in"
    tailcone_taper = 0.3
    x_engines = "52 ft"
    y_offset = 0.0
    dRadius = "15 in"
    unit_load_device = "LD3"
    min_top_cabin_height = "2 m"
    x_fixed_weight = "7ft"
    seat_height = "45 in"
    b_tail = 2.0
    floor_depth = "5.0 in"
    x_pressure_shell_fwd = "17 ft"
    x_end_cylinder = "97 ft"
    Nwebs = 1
    floor_distance = "0 in"
    x_nose_tip = "0 ft"

[Stabilizers]
lowspeed_cdf = 0.006
excrescence_drag_factor = 1.02
lowspeed_cdp = 0.0035
Re_ref = 1.0e7

    [Stabilizers.Htail]
    number_Htails = 2.0
    opt_move_wing = "min_static_margin"
    box_height_chord = 0.14
    nacelle_lift_curve_slope = 3.8
    downwash_factor = 0.6
    AR_Htail = 6.0
    sweep = 26.0
    opt_sizing = "fixed_Vh"
    x_Htail = "114.5 ft"
    SM_min = 0.05
    box_width_to_chord = 0.5
    added_weight_fraction = 0.3
    Vh = 1.45
    CD_Htail_from_center = 0.1
    CLh_max = 2.0
    multi_section = false
    center_box_halfspan = "2.5 ft"
    max_tail_download = -0.5
    CLh_at_max_forward_CG = -0.7
    CLh_spec = -0.02
    web_height_hbox = 0.75
    z_Htail = "0 ft"
    taper = 0.25

    [Stabilizers.Vtail]
    x_Vtail = "110 ft"
    box_height_chord = 0.14
    Vv = 0.1
    CLv_at_engine_out = 0.5
    number_Vtails = 1.0
    sweep = 25.0
    opt_sizing = "fixed_Vv"
    box_width_to_chord = 0.5
    added_weight_fraction = 0.4
    center_box_halfspan = 0.0
    web_height_hbox = 0.75
    CLv_max = 2.6
    AR_Vtail = 2.0
    taper = 0.3

[Fuel]
fuel_type = "LH2"
fuel_in_wing = false
fuel_usability_factor = 0.9
fuel_in_wingcen = false
fuel_enthalpy_vaporization = 0.0

    [Fuel.Storage]
    additional_mass_fraction = 0.1
    pressure_rise_factor = 2.0
    cruise_boiloff_rate = 0.4
    heat_leak_factor = 1.3
    inner_vessel_support_angle = "80 deg"
    inner_vessel_material = "Al-2219-T87"
    insulation_material = ["polyurethane32", "polyurethane32", "polyurethane32"]
    outer_vessel_support_angles = ["45 deg", "135 deg"]
    insulation_segment_base_thickness = [0.05, 0.05, 0.05]
    hold_departure = "0 h"
    tank_aspect_ratio = 2.0
    weld_efficiency = 0.9
    insulation_thicknesses_design_indices = [1, 2, 3]
    tank_placement = "rear"
    pressure_initial = "1.2 atm"
    sizes_insulation = true
    ullage_fraction = 0.05
    pressure_venting = "2 atm"
    hold_arrival = "0 h"
    outer_vessel_material = "Al-2219-T87"
    fuselage_clearance = "0.3 ft"

[LandingGear]
tailstrike_angle = "10 deg"
LG_nose_wheels_per_strut = 2
LG_nose_number_struts = 1
x_nose_landing_gear = "14ft"
LG_main_weight_fraction = 0.044
wing_dihedral_angle = "6 deg"
engine_ground_clearance = "23 in"
LG_nose_weight_fraction = 0.011
y_main_landing_gear_halfspan_fraction = 0.2
landing_gear_model = "mass_fractions"
x_main_landing_gear_offset = "1 ft"
LG_main_wheels_per_strut = 2
LG_main_number_struts = 2

[Options]
engine_location = "wing"
prop_sys_arch = "TF"

[Structures]
caps_max_avg_stress = 1.1
bending_max_avg_stress = 1.1
bending_safety_factor = 1.5
fuse_shell_modulus_ratio = 1.0
stress_factor = 1.0
caps_safety_factor = 1.5
skin_safety_factor = 3.0
floor_material = "TASOPT-Al"
wing_tail_cap_density = 2700.0
E_wing_spar_cap = "10e6 lbf/in2"
strut_density = 2700.0
sigma_caps = "30e3 lbf/in2"
webs_max_avg_stress = 1.1
E_struts = "10e6 lbf/in2"
tau_webs = "20e3 lbf/in2"
skin_material = "TASOPT-Al"
floor_max_avg_stress = 1.1
floor_safety_factor = 1.5
wing_tail_web_density = 2700.0
webs_material = "TASOPT-Al"
caps_material = "TASOPT-Al"
cone_max_avg_stress = 1.1
cone_safety_factor = 2.0
sigma_struts = "30e3 lbf/in2"
webs_safety_factor = 1.5
skin_max_avg_stress = 1.1
cone_material = "TASOPT-Al"
bending_material = "TASOPT-Al"

[Propulsion]
T_max_metal = 1280.0
Tt4_frac_top_of_climb = 0.2
Tt4_cruise = 1587.0
core_in_clean_flow = true
Tt4_takeoff = 1833.0
Tt4_frac_bottom_of_climb = 0.2
number_of_engines = 8

    [Propulsion.Nacelles]
    nacelle_pylon_wetted_area_ratio = 16.0
    nacelle_local_velocity_ratio = 1.02

    [Propulsion.Combustor]
    combustion_efficiency = 0.98

    [Propulsion.Weight]
    pylon_weight_fraction = 0.1
    engine_weight_delta = 0.0
    engine_access_weight_fraction = 0.3333333333333333
    weight_model = "fitzgerald_basic"
    custom_weight_delta = 8937.816445243663

    [Propulsion.Turbomachinery]
    M2 = 0.6
    HTR_fan = 0.3
    OPR = 30.0
    HTR_HPC = 0.8
    burner_PR = 0.94
    core_nozzle_PR = 0.989
    fan_eta_poly = 0.8948
    HPT_eta_poly = 0.889
    Kf_polyeff = -0.077
    high_spool_loss = 0.022
    BPR = 5.1
    LPC_PR = 2.5
    diffuser_PR = 0.998
    HTR_LPC = 0.6
    HPC_eta_poly = 0.87
    gear_ratio = 1.0
    LPT_eta_poly = 0.899
    Fan_PR = 1.685
    FPR0 = 1.685
    M25 = 0.6
    LPC_eta_poly = 0.88
    low_spool_loss = 0.01
    fan_nozzle_PR = 0.98

    [Propulsion.Offtakes]
    Tt_offtake_air = 300.0
    Low_spool_power_offtake_per_pax = 200.0
    LPC_mass_offtake_per_pax = 0.0063
    LPC_mass_offtake_per_max_mass = 0.0
    Low_spool_power_offtake_per_max_mass = 1.8
    Pt_offtake_air = 30000.0

    [Propulsion.Nozzles.core_nozzle_area]
    descentend = 1.0
    rotation = 1.0
    static = 1.0
    cutback = 1.0
    climbstart = 1.0
    climbend = 1.0
    descentstart = 1.0

    [Propulsion.Nozzles.fan_nozzle_area]
    descentend = 1.0
    rotation = 1.0
    static = 1.0
    cutback = 1.0
    climbstart = 1.0
    climbend = 1.0
    descentstart = 1.0

    [Propulsion.HeatExchangers]
    intercooler_inlet_mach = 0.1
    intercooler_order = 2
    precooler_order = 1
    regenerative_order = 4
    turbine_cooler_effectiveness = 0
    precooler_inlet_mach = 0.1
    turbine_cooler_inlet_mach = 0.02
    core_inner_diameter = "0.2 m"
    intercooler_effectiveness = 0
    maximum_heat_exchanger_length = "0.25 m"
    regenerative_effectiveness = 0.8
    turbine_cooler_order = 3
    regenerative_inlet_mach = 0.2
    has_recirculation = true
    recirculation_temperature = "200 K"
    added_mass_frac = 1.0
    precooler_effectiveness = 0

    [Propulsion.Cooling]
    hot_streak_T_allowance = 200.0
    t_film_cooling = 0.3
    HPT_efficiency_derivative_with_cooling = 0.0
    St = 0.09
    baseline_cooling_fraction = 0.0
    e_film_cooling = 0.7
    M41 = 0.9
    M_turbine_blade_exit = 1.0
    cooling_air_V_ratio = 0.15
